library(ggplot2)
install.packages("bnlearn")
install.packages("Rgraphviz")
install.packages('bnlearn')
install.packages('gmp')
install.packages('pcalg')
install.packages('Rccp')
install.packages('RBGL')
install.packages('igraph')
library(Rcpp)
library(gRain)
library(gRbase)
library(igraph)
library(RBGL)
library(dplyr)
library(magrittr)
library(RMySQL)
#########################################################
source("http://bioconductor.org/biocLite.R")
biocLite("Rgraphviz")


source("http://people.math.aau.dk/~sorenh/software/gR")
install.packages("gRbase")
install.packages("gRain")
install.packages("gRim")
library(Rcpp)

source("http://bioconductor.org/biocLite.R")
biocLite(c("graph", "Rgraphviz", "RBGL"))
install.packages("gRbase", dependencies=TRUE)

install.packages("gRain")
library(gRain)

library(gRbase)
install.packages('gRim')
library(gRim)
